create database customer_behaviour;
use customer_behaviour;
show tables;
select * from customer;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) as Revenue
FROM customer
GROUP by gender
ORDER BY Revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='yes' AND purchase_amount >
	(SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating),2) as Average_Review_Rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_Review_Rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, avg(purchase_amount) as Average_Purchase_Amount from customer
where shipping_type in ("Standard","Express")
GROUP BY shipping_type;
---- (OR)
SELECT shipping_type,AVG(purchase_amount) AS Average_Purchase_Amount
FROM customer
WHERE shipping_type = 'Standard'
   OR shipping_type = 'Express'
GROUP BY shipping_type
ORDER BY Average_Purchase_Amount DESC;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--- between subscribers and non-subsccribers.
SELECT subscription_status,COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS Avg_Spend,
ROUND(SUM(purchase_amount),2) AS Total_Revenue
FROM customer
GROUP BY subscription_status
ORDER BY Total_Revenue,AVG_Spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) AS Discount_Rate
FROM customer
GROUP BY item_purchased
ORDER BY Discount_Rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
WITH Customer_Type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases =1 THEN 'NEW'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS Customer_Segment
FROM customer
)
SELECT customer_segment,COUNT(*) AS Number_Of_Customers
FROM Customer_Type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_count as (
SELECT category,item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER( PARTITION BY CATEGORY ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category,item_purchased
)

SELECT item_rank,category,item_purchased,total_orders
FROM item_count
WHERE item_rank<= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,count(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases >5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group,sum(purchase_amount) as revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;

select * from customer;
